### ISSUE TITLE
Remove unused variable

### ISSUE THREAD

**Issue by S0Ulle33** [d34db33f-1007/asleep_scanner#1]
This list variable is created, but never used:
https://github.com/d34db33f-1007/asleep_scanner/blob/9572aa395ba90f0e27a8cea7606b6e6002c5b7ed/asleep.py#L34
Except when returning from function:
https://github.com/d34db33f-1007/asleep_scanner/blob/9572aa395ba90f0e27a8cea7606b6e6002c5b7ed/asleep.py#L106

The returned value of this function must be used to save the results. If this list is not filled in, it is worth changing the behavior of the function or deleting this variable at all.

**Comment by d34db33f-1007** [comment]
thank you!
fixed
